### ISSUE TITLE
Add date/time to note detail view

### ISSUE THREAD

**Issue by dkusznir** [dkusznir/blocnotes#7]
1.) Date/time created
2.) Date(s)/time(s) modified

**Comment by mhanlon** [comment]
You'll also want to make sure you use an `NSDateFormatter` to make that date look good (and it can even handle localization for you!).
```
    NSString *currentDateAndTime = [[self.detailItem valueForKey:@"timeStamp"] description];
    self.createdDateAndTime.text = [NSString stringWithFormat:@"Created At: %@", currentDateAndTime];
```

**Comment by dkusznir** [comment]
Fixed date/time format:

https://github.com/dkusznir/blocnotes/pull/15
